import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
  English: {
    LoginToYourAccount: 'Login to your account',
    EmailAddress: 'Email address',
    Password: 'Password',
    IForgotPassword: 'I forgot password',
    SignIn: 'Sign In',
    DontHaveAccountYet: 'Don\'t have account yet ?',
    SignUp: 'Sign Up',
    Schedule: 'Schedule',
    Media: 'Media',
    Playlist: 'Playlist',
    Radio: 'Radio',
    Overlay: 'Overlay',
    Admin: 'Admin',
    Users: 'Users',
    Profile: 'Profile',
    SignOut: 'Sign out',
    LogIn: 'Log In',
    NewEvent: 'New Event',
    EditEvent: 'Edit Event',
    Start: 'Start',
    End: 'End',
    RepeatDaily: 'Repeat daily',
    Create: 'Create',
    Cancel: 'Cancel',
    Update: 'Update',
    Delete: 'Delete',
    Today: 'Today',
    Month: 'Month',
    Week: 'Week',
    Day: 'Day',
    Overview: 'Overview',
    CreateNewAccount: 'Create new account',
    Name: 'Name',
    ConfirmPassword: 'Confirm Password',
    AlreadyHaveAccount: 'Already have account?',
    SignUpSucceed: 'Sign Up Succeed!',
    YouHaveSignedUpSuccessfully: 'You have been signed up successfully.',
    PleaseFindAnEmail: 'Please find an email on your email inbox.',
    Ok: 'Ok',
    ResetYourPassword: 'Reset your password',
    ResetPassword: 'Reset Password',
    Succeed: 'Succeed',
    PleaseCheckYourEmail: 'Please check your email inbox.',
    NewPassword: 'New Password',
    YourPasswordHasBeenReset: 'Your password has been reset.',
    ConfirmYourAccount: 'Confirm your account',
    VerifyAccount: 'Verify Account',
    VerifySucceed: 'Verify Succeed!',
    Remove: 'Remove',
    ago: 'ago',
    Edit: 'Edit',
    PowerdBy: 'Powered by',
    approved: 'approved',
    dismissed: 'dismissed',
    Approve: 'Approve',
    Dismiss: 'Dismiss',
    ManageUsers: 'Manage users',
    NO: 'No',
    Avatar: 'Avatar',
    Email: 'Email',
    Register: 'Register',
    Status: 'Status',
    Action: 'Action',
    Gallery: 'Gallery',
    Audio: 'Audio',
    Upload: 'Upload',
    Image: 'Image',
    ManageMedia: 'Manage media',
    of: 'of',
    medias: 'medias',
    CreateMedia: 'Create media',
    DeleteMedias: 'Delete medias',
    NewVideo: 'New Video',
    NewImage: 'New Image',
    NewGallery: 'New Gallery',
    NewWebsite: 'New Website',
    GroupName: 'Group Name',
    Rename: 'Rename',
    Position: 'Position',
    AnimationSpeed: 'Animation Speed',
    Width: 'Width',
    Height: 'Height',
    OrderNumber: 'Order Number',
    Font: 'Font',
    Size: 'Size',
    Color: 'Color',
    Text: 'Text',
    SaveElements: 'Save',
    Element: 'Element',
    Date: 'Date',
    Time: 'Time',
    ScrollText: 'Scroll Text',
    FadeText: 'Fade Text',
    StaticText: 'Static Text',
    CartText: 'Cart Text',
    ManageOverlays: 'Manage overlays',
    NewOverlay: 'New Overlay',
    Count: 'Count',
    CreatedAt: 'Created At',
    Prev: 'Prev',
    Next: 'Next',
    First: 'First',
    Last: 'Last',
    AddOrRemoveMedias: 'Add or Remove medias',
    SaveMediaOrder: 'Save media order',
    Save: 'Save',
    ManagePlaylists: 'Manage playlists',
    NewPlaylist: 'New Playlist',
    ChangeAvatar: 'Change Avatar',
    Reset: 'Reset',
    MyProfile: 'My Profile',
    Bio: 'Bio',
    EditRadioURL: 'Edit radio URL',
    StreamAddressInHttpDescription: 'Stream address in http or https format, mms streams are not supported!',
    Video: 'Video',
    Website: 'Website',
    Search: 'Search',
    user: 'user',
    Enter: 'Enter',
    email: 'email',
    name: 'name',
    password: 'password',
    EnterConfirmPassword: 'Enter confirm password',
    EnterNewPassword: 'Enter new password',
    TypeAudioSource: 'Type audio source',
    TypeDuration: 'Type duration',
    playlist: 'playlist',
    overlay: 'overlay',
    EnterYourPassword: 'Enter your password',
    EnterYourName: 'Enter your name',
    EnterYourBio: 'Enter your bio',
    TypeRadioUrl: 'Type radio url',
    seconds: 'seconds',
    minutes: 'minutes',
    hours: 'hours',
    days: 'days',
    weeks: 'weeks',
    months: 'months',
    years: 'years',
    Picture: 'Picture',
    Ticker: 'Ticker',
    Repeat: 'Repeat',
    TheUserHasBeenApproved: 'The user has been approved.',
    TheUserHasBeenDismissed: 'The user has been dismissed.',
    PasswordDoesNotMatch: 'Password does not match!',
    ServerConnectionError: 'Server connection error!',
    TheMediaHasBeenDeleted: 'The media has been deleted.',
    PleaseSelectAnImageToUpload: 'Please select an image to upload.',
    TheGalleryFileHasBeenUploaded: 'The gallery file has been uploaded.',
    GalleryMediaHasBeenCreated: 'Gallery media has been created.',
    GalleryMediaHasBeenUpdated: 'Gallery media has been updated.',
    AFileHasBeenDeleted: 'A file has been deleted.',
    ImageMediaHasBeenCreated: 'Image media has been created.',
    ImageMediaHasBeenUpdated: 'Image media has been updated.',
    TheAudioHasBeenUpdated: 'The audio has been updated.',
    PleaseSelectMediasToDelete: 'Please select medias to delete!',
    TheImageElementHasBeenUpdated: 'The image element has been updated.',
    TheOverlayGroupHasBeenCreated: 'The overlay group has been created.',
    TheOverlayGroupHasBeenUpdated: 'The overlay group has been updated.',
    TheEelementsHaveBeenSaved: 'The elements have been saved.',
    PleaseSelectAnElement: 'Please select an element!',
    TheElementsHaveBeenDeleted: 'The elements have been deleted.',
    AnElementHasBeenDeleted: 'An element have been created.',
    TheOverlayGroupHasBeenDeleted: 'The overlay group has been deleted.',
    APlaylistHasBeenCreated: 'A playlist has been created.',
    ThePlaylistHasBeenUpdated: 'The playlist has been updated.',
    ThePlaylistHasBeenDeleted: 'The playlist has been deleted.',
    AMediaHasBeenRemovedFromThePlaylist: 'A media has been removed from the playlist.',
    TheElementGroupHasBeenChanged: 'The element\'s group has been changed.',
    AvatarHasBeenUpdated: 'Avatar has been updated.',
    TheRadioURLHasBeenUpdated: 'The radio url has been updated.',
    PleaseSelectAPlaylist: 'Please select a playlist!',
    TheStartMustBeEailerThanTheEnd: 'The start must be eailer than the end!',
    PleaseSelectAMP4FileToUpload: 'Please select a mp4 file to upload.',
    VideoMediaHasBeenCreated: 'Video media has been created.',
    VideoMediaHasBeenUpdated: 'Video media has been updated.',
    WebsiteMediaHasBeenCreated: 'Website media has been created.',
    WebsiteMediaHasBeenUpdated: 'Website media has been updated.',
    AllTypes: 'All Types',
    AreYouSureToDeleteThisMedia: 'Are you sure to delete this media?',
    // added by Rpz
    AreYouSureToOverwriteThisMedia: 'Are you sure to Overwrite this media?',
    AreYouSureToDeleteThisElement: 'Are you sure to delete this element?',
    AreYouSureToDeleteThisGroup: 'Are you sure to delete this group?',
    AreYouSureToDeleteThisPlaylist: 'Are you sure to delete this playlist?',
    AreYouSureToRemoveThisMediaFromThePlaylist: 'Are you sure remove this media from the playlist?',
    Yes: 'Yes',
    No: 'No',
    playlists: 'playlists',
    Settings: 'Settings',
    SettingsHaveBeenUpdated: 'Settings have been updated successfully.',
    Footer: 'Footer',
    Copyright: 'Copyright',
    SoftwarePath: 'Software Path',
    TheDatabaseHasBeenCopied: 'The database has been copied to the software path.',
    TokenInvalid: 'The token is invalid or expired!',
    RepeatEnd: 'Repeat End',
    ShowScreenContent: 'Show Screen Content',
    Screen: 'Screen',
    ReloadImage: 'Reload Image',
    DeleteRepeats: 'Delete Repeats',
    DatabasePath: 'Database Path',
    ExePath: 'Exe Path',
    Duration: 'Duration',
    OwnAudio: 'Own Audio',
    MaxWidth: 'Max Width',
    MaxHeight: 'Max Height',
    MediaFiles: 'Media Files',
    PleaseSelectAudioSource: 'Please select audio source type.',
    PleaseTypeFontName: 'Please type font name.',
    PleaseSelectFontcolor: 'Please select fontcolor.',
    PleaseTypeAnimationspeed: 'Please type animationspeed.',
    PleaseTypeFontsize: 'Please type fontsize.',
    AnimationSpeedIsNotZero: 'Animation Speed must not be zero!',
    Logo: 'Logo',
    AuthLogo: 'Auth Logo',
  },
  German: {
    LoginToYourAccount: 'Ins Konto einloggen',
    EmailAddress: 'E-Mail-Addresse',
    Password: 'Passwort',
    IForgotPassword: 'Ich habe das Passwort vergessen',
    SignIn: 'Einloggen',
    DontHaveAccountYet: 'Hast du noch kein Konto?',
    SignUp: 'Anmelden',
    Schedule: 'Zeitplan',
    Media: 'Medien',
    Playlist: 'Wiedergabe',
    Radio: 'Rajio',
    Overlay: 'Überlagerung',
    Admin: 'Admin',
    Users: 'Benutzer',
    Profile: 'Profil',
    SignOut: 'Ausloggen',
    LogIn: 'Einloggen',
    NewEvent: 'Neues Event',
    EditEvent: 'Veranstaltung bearbeiten',
    Start: 'Starten',
    End: 'Ende',
    RepeatDaily: 'Wiederhole das täglich',
    Create: 'Erstellen',
    Cancel: 'Stornieren',
    Update: 'Aktualisieren',
    Delete: 'Löschen',
    Today: 'Heute',
    Month: 'Monat',
    Week: 'Woche',
    Day: 'Tag',
    Overview: 'Überblick',
    CreateNewAccount: 'Neuen Account erstellen',
    Name: 'Name',
    ConfirmPassword: 'Passwort bestätigen',
    AlreadyHaveAccount: 'Hast du schon einen Account?',
    SignUpSucceed: 'Melden Sie sich an!',
    YouHaveSignedUpSuccessfully: 'Sie wurden erfolgreich registriert.',
    PleaseFindAnEmail: 'Bitte finden Sie eine E-Mail in Ihrem E-Mail-Posteingang.',
    Ok: 'OK',
    ResetYourPassword: 'Setze dein Passwort zurück',
    ResetPassword: 'Passwort zurücksetzen',
    Succeed: 'Gelingen',
    PleaseCheckYourEmail: 'Bitte überprüfen Sie Ihre E-Mail-Posteingang.',
    NewPassword: 'Neues Kennwort',
    YourPasswordHasBeenReset: 'Dein Passwort wurde zurück gesetzt.',
    ConfirmYourAccount: 'Bestätigen Sie ihr Konto',
    VerifyAccount: 'Konto überprüfen',
    VerifySucceed: 'Bestätigen Sie Erfolg!',
    Remove: 'Löschen',
    ago: 'vor',
    Edit: 'Bearbeiten',
    PowerdBy: 'Unterstützt von',
    approved: 'genehmigt',
    dismissed: 'entlassen',
    Approve: 'Genehmigen',
    Dismiss: 'Entlassen',
    ManageUsers: 'Benutzer verwalten',
    NO: 'No',
    Avatar: 'Benutzerbild',
    Email: 'Email',
    Register: 'Registrieren',
    Status: 'Status',
    Action: 'Aktion',
    Gallery: 'Galerie',
    Audio: 'Audio',
    Upload: 'Hochladen',
    Image: 'Bild',
    ManageMedia: 'Medien verwalten',
    of: 'von',
    medias: 'Medien',
    CreateMedia: 'Erstellen Sie Medien',
    DeleteMedias: 'Medien teilen',
    NewVideo: 'Neues Video',
    NewImage: 'Neues Bild',
    NewGallery: 'Neue Galerie',
    NewWebsite: 'Neue Website',
    GroupName: 'Gruppenname',
    Rename: 'Umbenennen',
    Position: 'Position',
    AnimationSpeed: 'Animations Geschwindigkeit',
    Width: 'Breite',
    Height: 'Höhe',
    OrderNumber: 'Bestellnummer',
    Font: 'Schriftart',
    Size: 'Größe',
    Color: 'Farbe',
    Text: 'Text',
    SaveElements: 'Speichern',
    Element: 'Elemente',
    Date: 'Datum',
    Time: 'Zeit',
    ScrollText: 'Scrollen Sie Text',
    FadeText: 'Text ausblenden',
    StaticText: 'Statischer Text',
    CartText: 'Warenkorb Text',
    ManageOverlays: 'Overlays verwalten',
    NewOverlay: 'Neue Überlagerung',
    Count: 'Anzahl',
    CreatedAt: 'Hergestellt',
    Prev: 'Vorherige',
    Next: 'Nächster',
    First: 'Zuerst',
    Last: 'Zuletzt',
    AddOrRemoveMedias: 'Hinzufügen oder Entfernen von Medien',
    SaveMediaOrder: 'Medienauftrag speichern',
    Save: 'Sparen',
    ManagePlaylists: 'Verwalten Sie Wiedergabelisten',
    NewPlaylist: 'Neue Wiedergabeliste',
    ChangeAvatar: 'Avatar ändern',
    Reset: 'Zurücksetzen',
    MyProfile: 'Mein Profil',
    Bio: 'Bio',
    EditRadioURL: 'Radio-URL bearbeiten',
    StreamAddressInHttpDescription: 'Stream-Adresse im HTTP- oder HTTPS-Format, MMS-Streams werden nicht unterstützt!',
    Video: 'Videorekorder',
    Website: 'Website',
    Search: 'Suche',
    user: 'Benutzer',
    Enter: 'Eingabe',
    email: 'E-Mail',
    name: 'name',
    password: 'passwort',
    EnterConfirmPassword: 'Geben Sie Passwort bestätigen ein',
    EnterNewPassword: 'Geben Sie ein neues Passwort ein',
    TypeAudioSource: 'Audioquelle eingeben',
    TypeDuration: 'Geben Sie die Dauer ein',
    playlist: 'Wiedergabeliste',
    overlay: 'überlagern',
    EnterYourPassword: 'Gib dein Passwort ein',
    EnterYourName: 'Gib deinen Namen ein',
    EnterYourBio: 'Gib deine Biografie ein',
    TypeRadioUrl: 'Tippen Sie Radio-URL ein',
    seconds: 'Sekunden',
    minutes: 'Minuten',
    hours: 'Stunden',
    days: 'Tage',
    weeks: 'Wochen',
    months: 'Monate',
    years: 'Jahre',
    Picture: 'Bild',
    Ticker: 'Ticker',
    Repeat: 'Wiederholen',
    TheUserHasBeenApproved: 'Der Benutzer wurde genehmigt.',
    TheUserHasBeenDismissed: 'Der Benutzer wurde entlassen.',
    PasswordDoesNotMatch: 'Passwort stimmt nicht überein!',
    ServerConnectionError: 'Serververbindungsfehler!',
    TheMediaHasBeenDeleted: 'Das Medium wurde gelöscht.',
    PleaseSelectAnImageToUpload: 'Bitte wählen Sie ein Bild zum Hochladen.',
    TheGalleryFileHasBeenUploaded: 'Die Galerie-Datei wurde hochgeladen.',
    GalleryMediaHasBeenCreated: 'Galerie Medien wurden erstellt.',
    GalleryMediaHasBeenUpdated: 'Galerie Medien wurde aktualisiert.',
    AFileHasBeenDeleted: 'Eine Datei wurde gelöscht.',
    ImageMediaHasBeenCreated: 'Bildmedien wurden erstellt.',
    ImageMediaHasBeenUpdated: 'Bildmedien wurden aktualisiert.',
    TheAudioHasBeenUpdated: 'Das Audio wurde aktualisiert.',
    PleaseSelectMediasToDelete: 'Bitte wählen Sie Medien zum Löschen!',
    TheImageElementHasBeenUpdated: 'Das Bildelement wurde aktualisiert.',
    TheOverlayGroupHasBeenCreated: 'Die Überlagerungsgruppe wurde erstellt.',
    TheOverlayGroupHasBeenUpdated: 'Die Überlagerungsgruppe wurde aktualisiert.',
    TheEelementsHaveBeenSaved: 'Die Elemente wurden gespeichert.',
    PleaseSelectAnElement: 'Bitte wählen Sie ein Element aus!',
    TheElementsHaveBeenDeleted: 'Die Elemente wurden gelöscht.',
    AnElementHasBeenDeleted: 'Ein Element wurde erstellt.',
    TheOverlayGroupHasBeenDeleted: 'Die Überlagerungsgruppe wurde gelöscht.',
    APlaylistHasBeenCreated: 'Eine Playlist wurde erstellt.',
    ThePlaylistHasBeenUpdated: 'Die Playlist wurde aktualisiert.',
    ThePlaylistHasBeenDeleted: 'Die Wiedergabeliste wurde gelöscht.',
    AMediaHasBeenRemovedFromThePlaylist: 'Ein Medium wurde aus der Wiedergabeliste entfernt.',
    TheElementGroupHasBeenChanged: 'Die Gruppe des Elements wurde geändert.',
    AvatarHasBeenUpdated: 'Avatar wurde aktualisiert.',
    TheRadioURLHasBeenUpdated: 'Das Radio wurde aktualisiert.',
    PleaseSelectAPlaylist: 'Bitte wählen Sie eine Playlist!',
    TheStartMustBeEailerThanTheEnd: 'Der Start muss früher als das Ende sein!',
    PleaseSelectAMP4FileToUpload: 'Bitte wähle eine mp4 Datei zum hochladen aus.',
    VideoMediaHasBeenCreated: 'Videomedien wurden erstellt.',
    VideoMediaHasBeenUpdated: 'Videomedien wurden aktualisiert.',
    WebsiteMediaHasBeenCreated: 'Website-Medien wurden erstellt.',
    WebsiteMediaHasBeenUpdated: 'Website-Medien wurden aktualisiert.',
    AllTypes: 'Alle Arten',
    AreYouSureToDeleteThisMedia: 'Möchten Sie dieses Medium wirklich löschen?',
    // added by Rpz
    AreYouSureToOverwriteThisMedia: 'Möchten Sie dieses Medium wirklich Überschreiben?',
    AreYouSureToDeleteThisElement: 'Möchten Sie dieses Element wirklich löschen?',
    AreYouSureToDeleteThisGroup: 'Bist du sicher, diese Gruppe zu löschen?',
    AreYouSureToDeleteThisPlaylist: 'Bist du sicher, diese Playlist zu löschen?',
    AreYouSureToRemoveThisMediaFromThePlaylist: 'Bist du sicher, dass du dieses Medium aus der Playlist entfernst?',
    Yes: 'Ja',
    No: 'Nein',
    playlists: 'Wiedergabelisten',
    Settings: 'die Einstellungen',
    SettingsHaveBeenUpdated: 'Einstellungen wurden erfolgreich aktualisiert.',
    Footer: 'Fußzeile',
    Copyright: 'Urheberrechte',
    SoftwarePath: 'Softwarepfad',
    TheDatabaseHasBeenCopied: 'Die Datenbank wurde in den Softwarepfad kopiert.',
    TokenInvalid: 'Das Token ist ungültig oder abgelaufen!',
    RepeatEnd: 'Wiederholen Sie das Ende',
    ShowScreenContent: 'Bildschirminhalt anzeigen',
    Screen: 'Bildschirm',
    ReloadImage: 'Bild neu laden',
    DeleteRepeats: 'Wiederholungen löschen',
    DatabasePath: 'Datenbankpfad',
    ExePath: 'Exe Pfad',
    Duration: 'Dauer',
    OwnAudio: 'Eigenes Audio',
    MaxWidth: 'Maximale Breite',
    MaxHeight: 'Maximale Höhe',
    MediaFiles: 'Media-Dateien',
    PleaseSelectAudioSource: 'Bitte wählen Sie den Audioquellentyp.',
    PleaseTypeFontName: 'Bitte geben Sie den Namen der Schriftart ein.',
    PleaseSelectFontcolor: 'Bitte wählen Sie Schriftfarbe.',
    PleaseTypeAnimationspeed: 'Bitte geben Sie animationspeed ein.',
    PleaseTypeFontsize: 'Bitte geben Sie die Schriftgröße ein.',
    AnimationSpeedIsNotZero: 'Animationsgeschwindigkeit darf nicht Null sein!',
    Logo: 'Logo',
    AuthLogo: 'Auth Logo',
  }
});